### ISSUE TITLE
QUESTION: Cade o CSS?

### ISSUE THREAD

**Issue by altendorfme** [zapbr/personal#1]
Cade o Cansei de ser Sexy? Opa aqui é Cascading Style Sheets. ;)

**Comment by zapbr** [comment]
Infelizmente nunca fui ...
e a banda acabou, então ja eras

😭

**Comment by altendorfme** [comment]
Close issue por falta de banda.

**Comment by zapbr** [comment]
haha mas vc me lembrou daquele show do Móveis no Clube Tiete

https://github.com/zapbr/personal/blob/main/concerts.md#2012

🤘
